### PR TITLE
Improve build environment and documentation

### PR DESCRIPTION
**Pull request by amotl**
Dear Clemens,

this improves the build environment significantly. By just typing `make`, it will install the Arduino build environment, pull in all dependencies and build the whole thing based on [PlatformIO](https://platformio.org/).

Cheers,
Andreas.

### CODE REVIEW

**Comment by ClemensGruber** [comment]
Many thanks, Andreas! Is the lastest U8g2 the version 2.28.6? In my Arduino environment I got 2.27.6 as the highest only, so I'm asking myself is the 28 done intentionally or a typo? 

https://github.com/ClemensGruber/hani-mandl/blob/5f2f0402091dc90d87a7dc7138d9fdbf06649990/platformio.ini#L23

**Comment by amotl** [comment]
Hi Clemens,

version 2.28.6 is the most recent one according to `pio lib show`:
```
$ pio lib show U8g2
[...]
2.28.6, released Sat Apr 25 14:17:51 2020
```

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Clemens,

I've just rebased this on top of current master and invoking `make` still works like a charm on macOS. So, I consider this ready to be merged and also will be happy to hear back about whether it will add some benefit for your users and contributors.

With kind regards,
Andreas.

**Comment by ClemensGruber** [comment]
Many thanks @amotl! @MKO1640 has already mentioned PlatformIO for HaniMandl and I think he is willing to test it! ;-)

**Pull request merged**
